### ISSUE TITLE
Problem when npm start

### ISSUE THREAD

**Issue by abyeli** [alfficcadenti/splinterlands-bot#102]
Hi 
i have this message when i start the bot

> splinterlands-bot@1.10.0 start
> node main.js

isMultiAccountMode: false
Running mode: single
C:\Users\rig\Desktop\splinterlands-bot-master\main.js:73
    let account = process.env.ACCOUNT.split('@')[0]; // split @ to prevent email use
                                      ^

TypeError: Cannot read properties of undefined (reading 'split')
    at startSingle (C:\Users\rig\Desktop\splinterlands-bot-master\main.js:73:39)
    at C:\Users\rig\Desktop\splinterlands-bot-master\main.js:93:15
    at Object.<anonymous> (C:\Users\rig\Desktop\splinterlands-bot-master\main.js:95:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Can you help?

Thank you

**Comment by alfficcadenti** [comment]
likely you didn't setup the env file and/or the username variable in the file properly.
check the readme and use the env-example file being sure to rename the file in .env (dot at the beginning and no extension in the filename)
