### ISSUE TITLE
Error while click on card. Not every game

### ISSUE THREAD

**Issue by meloer** [alfficcadenti/splinterlands-bot#123]
btn--create-team clicked
Click cards iter-[1]
145clicked
play:  162
162 clicked
play:  403
157 clicked
play:  163
160 clicked
play:  161
161 clicked
play:  158
158 clicked
F:\splinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:342
            throw new Error('Node is either not clickable or not an HTMLElement');
                  ^

Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (F:\splinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:342:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ElementHandle.click (F:\splinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:415:26)
-------------------------------------------------------------

I try to restart or re-install but I still got this error many time after game  maintenance. (sep.14) In headless mode. Bot clicked on the card, but the card is not selected.

**Comment by meloer** [comment]
Some game complete but still have problem. Bot select all 6 card and complete game but in game some card is not selected.

**Comment by yatumnoo** [comment]
same problem
