### ISSUE TITLE
the bot cant get the json form site.

### ISSUE THREAD

**Issue by daskrs** [alfficcadenti/splinterlands-bot#19]
the site is not returning a valid json, i think it is offline or have a new api parameter. can you help me?

`API call:  https://splinterlands-data-service.herokuapp.com/battlesruleset?ruleset=Standard&mana=19&player=userbot
fetch  FetchError: invalid json response body at https://splinterlands-data-service.herokuapp.com/battlesruleset?ruleset=Standard&mana=19&player=userbot reason: Unexpected token < in JSON at position 0
    at C:\Users\user\Desktop\splinterlands-bot\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async battlesFilterByManacap (C:\Users\user\Desktop\splinterlands-bot\possibleTeams.js:75:21)
    at async Object.possibleTeams (C:\Users\user\Desktop\splinterlands-bot\possibleTeams.js:130:25)
    at async startBotPlayMatch (C:\Users\user\Desktop\splinterlands-bot\index.js:134:27)
    at async C:\Users\user\Desktop\splinterlands-bot\index.js:226:13 {
  type: 'invalid-json'
}`

**Comment by alfficcadenti** [comment]
Working now
