### ISSUE TITLE
Error while waiting for battle

### ISSUE THREAD

**Issue by ale6github** [alfficcadenti/splinterlands-bot#20]
I get this error after running the bot.

[Error while waiting for battle] TimeoutError: waiting for selector `.btn--create-team` failed: timeout 240000ms exceeded
    at new WaitTask (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:313:29)
    at Frame.waitForSelector (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51)
    at Page.waitForSelector (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2238:33)
    at startBotPlayMatch (xxxxsplinterlands-bot-master\index.js:76:16)
    at async xxxxsplinterlands-bot-master\index.js:162:13
Error:  TimeoutError: waiting for selector `.btn--create-team` failed: timeout 90000ms exceeded
    at new WaitTask (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:313:29)
    at Frame.waitForSelector (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51)
    at Page.waitForSelector (xxxxsplinterlands-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2238:33)
    at xxxxsplinterlands-bot-master\index.js:85:24
    at async startBotPlayMatch (xxxxsplinterlands-bot-master\index.js:76:5)
    at async xxxxsplinterlands-bot-master\index.js:162:13

**Comment by alfficcadenti** [comment]
it may be caused from different reasons, here few:
- login wasn't successful
- .env file wasn't created properly
- splinterlands didn't find a match for your account
- -...

**Comment by circle2014** [comment]
I get this error after running the bot too 
`Login
Quest:  {
  name: 'High Priority Targets',
  splinter: 'snipe',
  total: 5,
  completed: 5
}
no quest reward to be claimed
[Error while waiting for battle]
Refreshing the page and retrying to retrieve a battle
[Battle cannot start]: TimeoutError: waiting for selector `.btn--create-team` failed: timeout 90000ms exceeded
    at new WaitTask (C:\splinterlands-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (C:\splinterlands-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (C:\splinterlands-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\splinterlands-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:313:29)
    at Frame.waitForSelector (C:\splinterlands-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51)
    at Page.waitForSelector (C:\splinterlands-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2238:33)
    at C:\splinterlands-bot\index.js:87:24
    at async startBotPlayMatch (C:\splinterlands-bot\index.js:77:5)
    at async C:\splinterlands-bot\index.js:182:13
Error:  Error: The Battle cannot start
    at startBotPlayMatch (C:\splinterlands-bot\index.js:92:15)`

**Comment by alfficcadenti** [comment]
Download the latest version
