### ISSUE TITLE
Bug in the quest system

### ISSUE THREAD

**Issue by daskrs** [alfficcadenti/splinterlands-bot#22]
I try change to the new api, but the quest aways return me the same error.
I believe it's something simple to fix, but as i'm new to nodejs i really don't know how to fix it.

new api : https:/api2.splinterlands.com/players/quests?username=
`[ERROR QUEST] are you using username or email? please use username  TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\user\Desktop\splinterlands-bot\node_modules\node-fetch\lib\index.js:1305:9)
    at C:\Users\user\Desktop\splinterlands-bot\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\user\Desktop\splinterlands-bot\node_modules\node-fetch\lib\index.js:1407:9)
    at Object.getPlayerQuest (C:\Users\user\Desktop\splinterlands-bot\quests.js:23:39)
    at getQuest (C:\Users\user\Desktop\splinterlands-bot\index.js:34:19)
    at C:\Users\user\Desktop\splinterlands-bot\index.js:225:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by alfficcadenti** [comment]
The api is working but the app is not reading your username. Check you created the .env file properly
