### ISSUE TITLE
can get it to even start plz help

### ISSUE THREAD

**Issue by dyrt1** [alfficcadenti/splinterlands-bot#26]
have done everything mentioned just get this... it opens splinterlands goes to the sign in then doesnt type or anything reloads 5 times and closes what am i doing wrong...ty

Your environment has been set up for using Node.js 14.17.5 (ia32) and npm.

C:\Users\Owner>npm i

up to date, audited 69 packages in 577ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\Owner>node index.js
login error TypeError: text is not iterable
    at Keyboard.type (C:\Users\Owner\node_modules\puppeteer\lib\Input.js:160:24)
    at Keyboard.<anonymous> (C:\Users\Owner\node_modules\puppeteer\lib\helper.js:112:23)
    at ElementHandle.type (C:\Users\Owner\node_modules\puppeteer\lib\JSHandle.js:363:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DOMWorld.type (C:\Users\Owner\node_modules\puppeteer\lib\DOMWorld.js:422:5)
    at async Object.login (C:\Users\Owner\splinterlandsPage.js:4:9)
    at async startBotPlayMatch (C:\Users\Owner\index.js:24:5)
    at async Task.execution (C:\Users\Owner\index.js:143:9)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\Owner\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.type (C:\Users\Owner\node_modules\puppeteer\lib\DOMWorld.js:422:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.login (C:\Users\Owner\splinterlandsPage.js:4:9)
    at async startBotPlayMatch (C:\Users\Owner\index.js:24:5)
    at async Task.execution (C:\Users\Owner\index.js:143:9)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Owner\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.type (C:\Users\Owner\node_modules\puppeteer\lib\Page.js:1103:29)
    at C:\Users\Owner\splinterlandsPage.js:7:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.login (C:\Users\Owner\splinterlandsPage.js:4:9)
    at async startBotPlayMatch (C:\Users\Owner\index.js:24:5)
    at async Task.execution (C:\Users\Owner\index.js:143:9)
END Error:  TypeError: Cannot read property 'split' of undefined
    at startBotPlayMatch (C:\Users\Owner\index.js:36:67)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (C:\Users\Owner\index.js:143:9)

**Comment by circle2014** [comment]
Hi make sure your .env file is correct with no space.

**Comment by dyrt1** [comment]
so i got the .env to work but when it searches for a team its not returning from the site.. the problem isnt i dont have enough cards bc i have nearly 1 of every card when i look at the site it has an error 405 or something ..u know how to fix

**Comment by dyrt1** [comment]
ok so i found the problem guys ty vm for all the help.. u can close thread just one question why is there a 30 min wait and how can i make that lower then 30

**Comment by alfficcadenti** [comment]
"why is there a 30 min wait and how can i make that lower then 30" check the readme for the reasons.
you can change in the index.js line 169
