### ISSUE TITLE
bot stops

### ISSUE THREAD

**Issue by sijokaras** [alfficcadenti/splinterlands-bot#5]
bot stops after entering battle. doesnt click rumble button and after some time crashes

**Comment by alfficcadenti** [comment]
thanks for reporting @sijokaras for how splinterlands works, after the player enter the battle, the result is already generated so there is no need to click on "rumble".
btw I've just updated the code adding the cron function and with the current setup the player will play a battle every 15 minutes which will allow to keep the capture rate around 40%

**Comment by Benderreborn** [comment]
Could you tell me the reason why the bot hangs at this moment. The following errors are returned to the console.
![изображение](https://user-images.githubusercontent.com/51919093/127569761-ab5b920c-630e-4fb7-8939-c4e7b112668f.png)

**Comment by alfficcadenti** [comment]
@Benderreborn the bot is not able to retrieve the cards available for your accounts. 
try removing the initial '@' from the ACCOUNT in .env file

**Comment by Benderreborn** [comment]
> 
> 
> @Benderreborn the bot is not able to retrieve the cards available for your accounts.
> try removing the initial '@' from the ACCOUNT in .env file

Yes, it worked. Thanks.

**Comment by Benderreborn** [comment]
Hello. The bot does not want to create a team again. It outputs the following errors to the console.
![изображение](https://user-images.githubusercontent.com/51919093/127617676-7dfa40ea-1b12-4151-8095-4e9d4d535937.png)

**Comment by alfficcadenti** [comment]
in this case the bot is trying to give you a team based on your available cards and if it doesn't find one, it tries to check other possible teams with a lower mana. In this case it reached mana = 1 meaning that based on your playable cards, there were no team available to be played. 
You should increase you deck buying or renting some of the most used cards. (Goblin Mech, Furious chicken, Elven Cuttroath,...) as a reference you may want to have a look at one of the basic accounts I run with the bot [@splinterlava ](https://splinterlands.com/?p=collection&a=splinterlava)

**Comment by Benderreborn** [comment]
He started the report with 24 mana. As I understand it, it accesses the site with certain data, for example https://splinterlands-data-service.herokuapp.com/battlesruleset?ruleset=Standart&mana=24 and he doesn't get an answer from there. I am right now in the browser clicking on this link also do not receive any data. But there was a period of time when the data was returned correctly.

**Comment by alfficcadenti** [comment]
the correct url is https://splinterlands-data-service.herokuapp.com/battlesruleset?ruleset=Standard&mana=24 (check typo) and there is a list of 1200 possible teams but likely, every team has one card that you don't have

**Comment by Benderreborn** [comment]
Yes, that's right. I checked this badly just now. But when an error was issued, I copied the entire path from the console and received a blank in response as well. But okay, it's working now. Thank you very much.

**Comment by laxmanmah** [comment]
Would you please tell me step to run the bot? Thank you

**Comment by alfficcadenti** [comment]
@laxmanmah you can clone the repo, create the file '.env' where you specified your credentials like this:
    ACCOUNT=youremail@email.com
    PASSWORD=yourpassword

then run:
npm install
npm start

(you need nodejs installed)

**Comment by laxmanmah** [comment]
> @laxmanmah you can clone the repo, create the file '.env' where you specified your credentials like this:
> ACCOUNT=[youremail@email.com](mailto:youremail@email.com)
> PASSWORD=yourpassword
> 
> then run:
> npm install
> npm start
> 
> (you need nodejs installed)

Thank you for your hard work. will you please help me

root@kali:~/splinterlands-bot# npm start

> splinter-scraper@1.0.0 start /root/splinterlands-bot
> node index.js

Error: Failed to launch the browser process!
[6908:6908:0802/100000.111595:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/splinterlands-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
    at ChildProcess.<anonymous> (/root/splinterlands-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:79)
    at ChildProcess.emit (events.js:412:35)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

**Comment by alfficcadenti** [comment]
@laxmanmah can you please try `node index.js` instead of `npm start` and let me know

**Comment by Pyxels** [comment]
Try running it with a user instead of root.

> 6908:6908:0802/100000.111595:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported.

**Comment by Pyxels** [comment]
else you could add the following args in the index.js

const browser = await puppeteer.launch({
    headless: false,
    args: ['--no-sandbox']
});

**Comment by laxmanmah** [comment]
> @laxmanmah can you please try `node index.js` instead of `npm start` and let me know

Are you available on telegram or somewhere I can chat.

**Comment by alfficcadenti** [comment]
> Are you available on telegram or somewhere I can chat.

search for `splinterlands bot` in telegram I've just created a group

**Comment by laxmanmah** [comment]
You are awesome

**Comment by rosales2710** [comment]
sorry that bot just work on linux?

**Comment by ravau** [comment]
I believe this bot works also with user and posting key?

Anyway, not sure how to solve this problem, after using npm start:

![obraz](https://user-images.githubusercontent.com/13334285/131368341-ac65c018-81d5-4337-93c2-7e9d3f53f79f.png)

I have installed the repo before running it, of course.

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v8.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle splinter-scraper@1.0.0~prestart: splinter-scraper@1.0.0
6 info lifecycle splinter-scraper@1.0.0~start: splinter-scraper@1.0.0
7 verbose lifecycle splinter-scraper@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle splinter-scraper@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/splinterlands-bot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle splinter-scraper@1.0.0~start: CWD: /root/splinterlands-bot
10 silly lifecycle splinter-scraper@1.0.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle splinter-scraper@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle splinter-scraper@1.0.0~start: Failed to exec start script
13 verbose stack Error: splinter-scraper@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid splinter-scraper@1.0.0
15 verbose cwd /root/splinterlands-bot
16 verbose Linux 2.6.32-042stab142.1
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.17.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error splinter-scraper@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the splinter-scraper@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by alfficcadenti** [comment]
@ravau it seems an error with the code... probably you edited the index.js by mistake... pull the new code and it will work.
And yes, you must use username and posting key for the bot

**Comment by alek-tech** [comment]
Salve alfredo mi chiamo Alessandro e faccio il proggrammatore in python
chiedo scusa se la disturbo ma non ho trovato altro modo di contattarla allora, io sto facendo lo stesso bot in python per un cliente online e appena ora ho visto che qualcosa esiste gia
Le andrebbe forse di spiegarmi quale e il suo metodo per la scelta delle carte vincenti?
la ringrazio tanto e complimenti per il bot.
Cordiali saluti
Alessandro

**Comment by kantarin** [comment]
help me ?

Routine error at:  9/12/2021, 1:12:35 AM Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).
    at ChromeLauncher.launch (D:\Programer\Splinterlands\splinterlands-bot\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:88:27)
    at async D:\Programer\Splinterlands\splinterlands-bot\index.js:229:29
aecheers@gmail.com waiting for the next battle in 30  minutes at  9/12/2021, 1:42:35 AM
If you need support for the bot, join the telegram group https://t.me/splinterlandsbot and discord https://discord.gg/bR6cZDsFSX,  dont pay scammers
