### ISSUE TITLE
Error: No node found for selector: .btn--create-team

### ISSUE THREAD

**Issue by scorpius81** [alfficcadenti/splinterlands-bot#83]
I recive this error: In home page i see battle win but the report is empty as if I had won by abandonment

Play this for the quest: [
  '156',
  [
    156, 152,    191,
    36,  62,     35,
    34,  'life', '',
    ''
  ]
]

/home/xxxx/bot-splinter/splinterlands-bot-1.1.0/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: No node found for selector: .btn--create-team
    at Object.assert (/home/xxxx/bot-splinter/splinterlands-bot-1.1.0/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click (/home/xxxx/bot-splinter/splinterlands-bot-1.1.0/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:277:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.1.0

**Comment by alfficcadenti** [comment]
try to update the bot
